### ISSUE TITLE
Nil pointer error while creating a logstream

### ISSUE THREAD

**Issue by podiyan** [bradgignac/logspout-cloudwatch#17]
I'm getting a nil pointer error, possibly due to AWS API changes. 

Per AWS api doc cloudwatchlogs.New expects a session config provider 

**panic: runtime error: invalid memory address or nil pointer dereference**
[signal 0xb code=0x1 addr=0x20 pc=0x5d4ea6]

goroutine 16 [running]:
runtime.panic(0x846b20, 0xb2c213)
    /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
**github.com/aws/aws-sdk-go/service/cloudwatchlogs.New(0x0, 0x0, 0x0, 0x0, 0x0, 0xc20806f570)**
    /go/src/github.com/aws/aws-sdk-go/service/cloudwatchlogs/service.go:72 +0x76
**github.com/bradgignac/logspout-cloudwatch.NewLogStream(0x7ffc3c41df55, 0x9, 0xc208037010, 0xc, 0xc20806f868, 0x0, 0x0)**
    /go/src/github.com/bradgignac/logspout-cloudwatch/logstream.go:20 +0x52
github.com/bradgignac/logspout-cloudwatch.NewAdapter(0xc208042360, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/bradgignac/logspout-cloudwatch/cloudwatch.go:49 +0x105
github.com/gliderlabs/logspout/router.(_RouteManager).Add(0xc208022db0, 0xc208042360, 0x0, 0x0)
    /go/src/github.com/gliderlabs/logspout/router/routes.go:117 +0x203
github.com/gliderlabs/logspout/router.(_RouteManager).AddFromUri(0xc208022db0, 0x7ffc3c41df48, 0x16, 0x0, 0x0)
    /go/src/github.com/gliderlabs/logspout/router/routes.go:107 +0x354
github.com/gliderlabs/logspout/router.(*RouteManager).Setup(0xc208022db0, 0x0, 0x0)
    /go/src/github.com/gliderlabs/logspout/router/routes.go:186 +0x1bb
main.main()
    /go/src/github.com/gliderlabs/logspout/logspout.go:39 +0x646

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
    /usr/lib/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
    /usr/lib/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

**Comment by bradgignac** [comment]
Hi @podiyan, this was caused by a recent update to the AWS Golang SDK. I have a branch almost ready to go that will resolve the issue along with a few other CloudWatch error conditions I've run into. Hope that helps!

**Comment by podiyan** [comment]
Yes, just noticed your PR #16  That'd help.
Thanks for sharing logspout-cloudwatch this fits my requirements exactly :). Much better and organized than what i was attempting to do.

**Comment by podiyan** [comment]
Do you plan to merge PR 16 soon?

**Comment by bradgignac** [comment]
@podiyan I should be able to get it merged this week. I really want to get it in this evening, but I'm traveling so it's hard to make a firm commitment.

**Comment by podiyan** [comment]
Thanks @bradgignac. 

Looking forward to your merge.

**Comment by podiyan** [comment]
Forked code to do some tests, I could see that the issue is fixed with PR 16.
Thanks
