### ISSUE TITLE
When would you need port 8000 exposed?

### ISSUE THREAD

**Issue by jlchereau** [bradgignac/logspout-cloudwatch#19]
Hello,

I am currently testing this project against logentries docker container and I am definitely not a logspout expert. Nervertheless I got it working in 15 minutes and it proved reliable so far (a week of slow traffic).

I am not sure why you would need port 8000 exposed?

Regards,
J

**Comment by bradgignac** [comment]
@jlchereau Glad it is working for you! This Logspout adapter doesn't require that port 8000 is exposed. However, I use the Dockerfile from the main Logspout repository (https://github.com/gliderlabs/logspout/blob/master/Dockerfile) to build my container. It uses port 8000 to expose the router API.
